---
abstract: 'report interesting return values'
author:
  - 'Thomas Klausner <domm@cpan.org>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
  Test::Most: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-ReturnValue
requires:
  Archive::Any: 0
  Data::Dumper: 0
  Encode: 0
  File::Copy: 0
  File::Find: 0
  File::Path: 0
  File::Temp: 0
  JSON: 0
  Moose: 0
  MooseX::Getopt: 0
  MooseX::Types::Path::Class: 0
  PPI: 0
  Parse::CPAN::Packages: 0
  Path::Class: 0
  URI::Escape: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  homepage: http://returnvalues.useperl.at
  repository: git://github.com/domm/Acme-ReturnValue.git
version: 1.000
