---
name: Acme-ReturnValue
version: 0.70.0
author:
  - 'Thomas Klausner <domm@cpan.at>'
abstract: report interesting module return values
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Acme-ReturnValue
  homepage: http://returnvalues.useperl.at
  license: http://dev.perl.org/licenses/
  repository: http://github.com/domm/Acme-ReturnValue
requires:
  Archive::Any: 0.093
  Moose: 0.77
  MooseX::Getopt: 0.18
  PPI: 1.118
  Parse::CPAN::Packages: 2.31
  Path::Class: 0.16
  YAML::Any: 0.67
build_requires:
  Test::Most: 0.21
provides:
  Acme::ReturnValue:
    file: lib/Acme/ReturnValue.pm
    version: 0.70.0
  Acme::ReturnValue::MakeSite:
    file: lib/Acme/ReturnValue/MakeSite.pm
    version: 0.70.0
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
